"""
guess_right: un motore di autodiff in stile PyTorch
"""

from __future__ import annotations

import collections.abc
import typing

import numpy as np

__all__: list[str] = [
    "BinaryCrossEntropy",
    "CrossEntropy",
    "Dataset",
    "LeakyReLU",
    "Linear",
    "Loader",
    "Loss",
    "MeanSquaredError",
    "Model",
    "Module",
    "Optimizer",
    "Parameter",
    "ReLU",
    "Residual",
    "Sigmoid",
    "Softmax",
    "StochasticGradientDescent",
    "Tanh",
    "Tensor",
    "accuracy_score",
    "cos",
    "exp",
    "log",
    "matmul",
    "maximum",
    "mean",
    "minimum",
    "pow",
    "product",
    "round",
    "sin",
    "sum",
    "tanh",
]

class BinaryCrossEntropy(Loss):
    def __init__(self) -> None: ...

class CrossEntropy(Loss):
    def __init__(self) -> None: ...

class Dataset:
    def __init__(
        self,
        inputs: collections.abc.Sequence[Tensor],
        targets: collections.abc.Sequence[Tensor],
    ) -> None: ...
    def __len__(self) -> int: ...
    def size(self) -> int: ...
    @property
    def inputs(self) -> list[Tensor]: ...
    @property
    def targets(self) -> list[Tensor]: ...

class LeakyReLU(Module):
    def __init__(self) -> None: ...

class Linear(Module):
    def __init__(
        self,
        in_features: typing.SupportsInt | typing.SupportsIndex,
        out_features: typing.SupportsInt | typing.SupportsIndex,
    ) -> None: ...

class Loader:
    def __init__(
        self,
        dataset: Dataset,
        batch_size: typing.SupportsInt | typing.SupportsIndex = 1,
        shuffle: bool = False,
    ) -> None: ...
    def __len__(self) -> int: ...
    def get(self) -> Dataset: ...
    def size(self) -> int: ...

class Loss:
    @typing.overload
    def __call__(self, arg0: Tensor, arg1: Tensor) -> Tensor: ...
    @typing.overload
    def __call__(
        self,
        arg0: collections.abc.Sequence[Tensor],
        arg1: collections.abc.Sequence[Tensor],
    ) -> Tensor: ...

class MeanSquaredError(Loss):
    def __init__(self) -> None: ...

class Model(Module):
    def __init__(self) -> None: ...
    def add_leaky_relu(self) -> None: ...
    def add_linear(
        self,
        in_features: typing.SupportsInt | typing.SupportsIndex,
        out_features: typing.SupportsInt | typing.SupportsIndex,
    ) -> None: ...
    def add_relu(self) -> None: ...
    def add_residual(self, block: Residual) -> None: ...
    def add_sigmoid(self) -> None: ...
    def add_softmax(self) -> None: ...
    def add_tanh(self) -> None: ...

class Module:
    @typing.overload
    def __call__(self, arg0: Tensor) -> Tensor: ...
    @typing.overload
    def __call__(self, arg0: collections.abc.Sequence[Tensor]) -> list[Tensor]: ...
    @typing.overload
    def forward(self, arg0: Tensor) -> Tensor: ...
    @typing.overload
    def forward(self, arg0: collections.abc.Sequence[Tensor]) -> list[Tensor]: ...
    def parameters(self) -> list[Parameter]: ...

class Optimizer:
    def parameters(self) -> list[Parameter]: ...
    def step(self) -> None: ...
    def zero_grad(self) -> None: ...

class Parameter(Tensor):
    def __init__(
        self,
        data: typing.Any,
        requires_grad: bool = True,
        weight_decay: typing.SupportsFloat | typing.SupportsIndex = 1.0,
    ) -> None: ...
    @property
    def weight_decay(self) -> float: ...

class ReLU(Module):
    def __init__(self) -> None: ...

class Residual(Module):
    def __init__(self) -> None: ...
    def add_leaky_relu(self) -> None: ...
    def add_linear(
        self,
        in_features: typing.SupportsInt | typing.SupportsIndex,
        out_features: typing.SupportsInt | typing.SupportsIndex,
    ) -> None: ...
    def add_relu(self) -> None: ...
    def add_residual(self, block: Residual) -> None: ...
    def add_sigmoid(self) -> None: ...
    def add_softmax(self) -> None: ...
    def add_tanh(self) -> None: ...

class Sigmoid(Module):
    def __init__(self) -> None: ...

class Softmax(Module):
    def __init__(self) -> None: ...

class StochasticGradientDescent(Optimizer):
    def __init__(
        self,
        parameters: collections.abc.Sequence[Parameter],
        learning_rate: typing.SupportsFloat
        | typing.SupportsIndex = 0.0010000000474974513,
    ) -> None: ...

class Tanh(Module):
    def __init__(self) -> None: ...

class Tensor:
    @staticmethod
    def eye(
        dim: typing.SupportsInt | typing.SupportsIndex, requires_grad: bool = False
    ) -> Tensor: ...
    @staticmethod
    def linspace(
        start: typing.SupportsFloat | typing.SupportsIndex,
        end: typing.SupportsFloat | typing.SupportsIndex,
        samples: typing.SupportsInt | typing.SupportsIndex = 50,
        requires_grad: bool = False,
    ) -> Tensor: ...
    @staticmethod
    def normal(
        shape: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] = [],
        mu: typing.SupportsFloat | typing.SupportsIndex = 0.0,
        sigma: typing.SupportsFloat | typing.SupportsIndex = 1.0,
        requires_grad: bool = False,
    ) -> Tensor: ...
    @staticmethod
    def ones(
        shape: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] = [],
        requires_grad: bool = False,
    ) -> Tensor: ...
    @staticmethod
    def ones_like(other: Tensor, requires_grad: bool = False) -> Tensor: ...
    @staticmethod
    def seed(seed: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @staticmethod
    def uniform(
        shape: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] = [],
        a: typing.SupportsFloat | typing.SupportsIndex = 0.0,
        b: typing.SupportsFloat | typing.SupportsIndex = 1.0,
        requires_grad: bool = False,
    ) -> Tensor: ...
    @staticmethod
    def zeros(
        shape: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] = [],
        requires_grad: bool = False,
    ) -> Tensor: ...
    @staticmethod
    def zeros_like(other: Tensor, requires_grad: bool = False) -> Tensor: ...
    @typing.overload
    def __add__(self, arg0: Tensor) -> Tensor: ...
    @typing.overload
    def __add__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor: ...
    def __iadd__(self, arg0: Tensor) -> Tensor: ...
    def __imul__(self, arg0: Tensor) -> Tensor: ...
    def __init__(self, data: typing.Any, requires_grad: bool = False) -> None: ...
    def __isub__(self, arg0: Tensor) -> Tensor: ...
    def __itruediv__(self, arg0: Tensor) -> Tensor: ...
    def __matmul__(self, arg0: Tensor) -> Tensor: ...
    @typing.overload
    def __mul__(self, arg0: Tensor) -> Tensor: ...
    @typing.overload
    def __mul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    @typing.overload
    def __pow__(self, arg0: Tensor) -> Tensor: ...
    @typing.overload
    def __pow__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor: ...
    def __radd__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor: ...
    def __repr__(self) -> str: ...
    def __rmul__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor: ...
    def __rsub__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor: ...
    def __rtruediv__(
        self, arg0: typing.SupportsFloat | typing.SupportsIndex
    ) -> Tensor: ...
    @typing.overload
    def __sub__(self, arg0: Tensor) -> Tensor: ...
    @typing.overload
    def __sub__(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> Tensor: ...
    @typing.overload
    def __truediv__(self, arg0: Tensor) -> Tensor: ...
    @typing.overload
    def __truediv__(
        self, arg0: typing.SupportsFloat | typing.SupportsIndex
    ) -> Tensor: ...
    def backward(self) -> None: ...
    def item(self) -> float: ...
    def numpy(self) -> np.typing.NDArray[np.float32]: ...
    def transpose(self) -> Tensor: ...
    def zero_grad(self) -> None: ...
    @property
    def T(self) -> Tensor: ...
    @property
    def grad(self) -> np.typing.NDArray[np.float32]: ...
    @property
    def is_scalar(self) -> bool: ...
    @property
    def ndim(self) -> int: ...
    @property
    def requires_grad(self) -> bool: ...
    @property
    def shape(self) -> tuple[int, int]: ...
    @property
    def size(self) -> int: ...

def _no_grad_enabled() -> bool: ...
def _set_no_grad(arg0: bool) -> None: ...
def accuracy_score(
    predicted: collections.abc.Sequence[Tensor],
    target: collections.abc.Sequence[Tensor],
) -> float: ...
def cos(arg0: Tensor) -> Tensor: ...
def exp(arg0: Tensor) -> Tensor: ...
def log(arg0: Tensor) -> Tensor: ...
def matmul(arg0: Tensor, arg1: Tensor) -> Tensor: ...
@typing.overload
def maximum(arg0: Tensor, arg1: Tensor) -> Tensor: ...
@typing.overload
def maximum(
    arg0: typing.SupportsFloat | typing.SupportsIndex, arg1: Tensor
) -> Tensor: ...
@typing.overload
def maximum(
    arg0: Tensor, arg1: typing.SupportsFloat | typing.SupportsIndex
) -> Tensor: ...
def mean(arg0: Tensor) -> Tensor: ...
@typing.overload
def minimum(arg0: Tensor, arg1: Tensor) -> Tensor: ...
@typing.overload
def minimum(
    arg0: typing.SupportsFloat | typing.SupportsIndex, arg1: Tensor
) -> Tensor: ...
@typing.overload
def minimum(
    arg0: Tensor, arg1: typing.SupportsFloat | typing.SupportsIndex
) -> Tensor: ...
@typing.overload
def pow(arg0: Tensor, arg1: Tensor) -> Tensor: ...
@typing.overload
def pow(arg0: Tensor, arg1: typing.SupportsFloat | typing.SupportsIndex) -> Tensor: ...
def product(arg0: Tensor) -> Tensor: ...
def round(arg0: Tensor) -> Tensor: ...
def sin(arg0: Tensor) -> Tensor: ...
def sum(arg0: Tensor) -> Tensor: ...
def tanh(arg0: Tensor) -> Tensor: ...
